# Generated by Django 5.0.2 on 2024-02-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='conmment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
