# Generated by Django 5.0.2 on 2024-02-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_conmment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='conmment',
            new_name='content',
        ),
    ]
